AWSTemplateFormatVersion: '2010-09-09'
Description: Production Network Infrastructure and Web Server for Plan-Letting Platform

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

Resources:
  PlanLettingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.18.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: PlanLetting-Production-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PlanLetting-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: PlanLettingVPC
    Properties:
      VpcId: !Ref PlanLettingVPC
      InternetGatewayId: !Ref InternetGateway

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      VpcId: !Ref PlanLettingVPC
      CidrBlock: 172.18.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PlanLetting-Private-Subnet-AZ1

  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      VpcId: !Ref PlanLettingVPC
      CidrBlock: 172.18.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PlanLetting-Public-Subnet-AZ2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: InternetGateway
    Properties:
      VpcId: !Ref PlanLettingVPC
      Tags:
        - Key: Name
          Value: PlanLetting-Public-RouteTable

  PublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref PublicRouteTable

  PublicWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and HTTPS traffic from anywhere
      VpcId: !Ref PlanLettingVPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic from anywhere
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          Description: Allow HTTPS
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      Tags:
        - Key: Name
          Value: PlanLetting-Web-SG

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0e34b50e714a297f1
      Monitoring: false
      SubnetId: !Ref PublicSubnetAZ2
      SecurityGroupIds:
        - !Ref PublicWebSecurityGroup
        
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo dnf update -y
          sudo dnf install httpd -y
          sudo systemctl enable httpd
          sudo systemctl start httpd
      Tags:
        - Key: Name
          Value: PlanLetting-Apache-WebServer

Outputs:
  InstancePublicIP:
    Description: Public IP of the Web Server
    Value: !GetAtt WebServerInstance.PublicIp