paramName:
  CustomKey: 
    Description: KeyPairName
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  testvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.18.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: testvpc
TestIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: TestIGW
TestVPCGWAttachment:
    DependsOn: testvpc
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref testvpc
      InternetGatewayId: !Ref TestIGW
TestPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      availabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref testvpc
      CidrBlock: 172.18.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: TestPrivateSubnet
TestPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      availabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref testvpc
      CidrBlock: 172.18.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: TestPublicSubnet1
TestPublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: TestIGW
    Properties:
      VpcId: !Ref testvpc
      Tags:
        - Key: Name
          Value: TestPublicRouteTable
TestPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: TestVPCGWAttachment
    Properties:
      RouteTableId: !Ref TestPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref TestIGW
TestPublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TestPublicSubnet
      RouteTableId: !Ref TestPublicRouteTable
TestWebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EnduroWebSG
      VpcId: !Ref testvpc
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic from anywhere
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          Description: Allow HTTPS
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      tags:
        - Key: Name
          Value: TestWebSG Ruke
TestWebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref CustomKey
      ImageId: ami-0e34b50e714a297f1
      Monitoring: false
      SubnetId: !Ref TestPublicSubnet1
      SecurityGroupIds:
        - !Ref TestWebSG
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo dnf update -y
          sudo dnf install httpd -y
          sudo systemctl enable httpd
          sudo systemctl start httpd
          
        Tags:
          - Key: Name
            Value: ApacheWebServer
Outputs:
  InstancePublicIP:
  Description: Public IP of Web Server
  Value: !GetAtt testWebServer.pubplicIP
