AWSTemplateFormatVersion: '2010-09-09'
Description: 
  Stack 1 - Plan-Letting Network Infrastructure. 
  Provisions VPC A (Public Services) and VPC B (Private Services), VPC Peering, Routing, and Security Groups.

Resources:
  # VPC A Public Services 
  VPCA:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-Frontend

  VPCAInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-IGW

  VPCAIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCA
      InternetGatewayId: !Ref VPCAInternetGateway

 # VPC A - Public Subnets which i will connec to the ALB 
  VPCAPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPCA
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-Pub-AZ1

  VPCAPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPCA
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-Pub-AZ2
          
 # VPC A - Private Subnets for the Web ASG 
  VPCAPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPCA
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-Priv-AZ1

  VPCAPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPCA
      CidrBlock: 10.0.12.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-Priv-AZ2
  
  # NAT Gateway for VPC A Private Subnets so packages can be downaloded 
  VPCANatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  VPCANatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt VPCANatEIP.AllocationId
      SubnetId: !Ref VPCAPublicSubnet1
      Tags:
        - Key: Name
          Value: PlanLetting-VPCA-NAT

  # VPC B Private Services for Backend & Management ec2
 
  VPCB:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: PlanLetting-VPCB-Backend

  # VPC B  Private Subnets For RDS and Management EC2
  VPCBPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPCB
      CidrBlock: 10.1.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PlanLetting-VPCB-Priv-AZ1

  VPCBPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPCB
      CidrBlock: 10.1.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PlanLetting-VPCB-Priv-AZ2

 # VPC Peering & Routing

  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerVpcId: !Ref VPCB
      VpcId: !Ref VPCA
      Tags:
        - Key: Name
          Value: PlanLetting-VPC-Peering

# Route Tables - VPC A Public
  VPCAPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCA
      Tags:
        - Key: Name
          Value: VPCA-Public-RT
          
  VPCAPubRouteToIGW:
    Type: AWS::EC2::Route
    DependsOn: VPCAIGWAttachment
    Properties:
      RouteTableId: !Ref VPCAPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref VPCAInternetGateway

  VPCAPubRouteToVPCB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref VPCAPublicRouteTable
      DestinationCidrBlock: 10.1.0.0/16
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  VPCAPubSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPCAPublicSubnet1
      RouteTableId: !Ref VPCAPublicRouteTable

  VPCAPubSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPCAPublicSubnet2
      RouteTableId: !Ref VPCAPublicRouteTable

  # Route Tables - VPC A Private
  VPCAPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCA
      Tags:
        - Key: Name
          Value: VPCA-Private-RT

  VPCAPrivRouteToNAT:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref VPCAPrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref VPCANatGateway

  VPCAPrivRouteToVPCB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref VPCAPrivateRouteTable
      DestinationCidrBlock: 10.1.0.0/16
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  VPCAPrivSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPCAPrivateSubnet1
      RouteTableId: !Ref VPCAPrivateRouteTable

  VPCAPrivSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPCAPrivateSubnet2
      RouteTableId: !Ref VPCAPrivateRouteTable

  # Route Tables - VPC B Private
  VPCBPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCB
      Tags:
        - Key: Name
          Value: VPCB-Private-RT

  VPCBPrivRouteToVPCA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref VPCBPrivateRouteTable
      DestinationCidrBlock: 10.0.0.0/16
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  VPCBPrivSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPCBPrivateSubnet1
      RouteTableId: !Ref VPCBPrivateRouteTable

  VPCBPrivSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref VPCBPrivateSubnet2
      RouteTableId: !Ref VPCBPrivateRouteTable

  # Security Groups
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP and HTTPS to ALB
      VpcId: !Ref VPCA
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PlanLetting-ALB-SG

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH into Bastion from AWS Console
      VpcId: !Ref VPCA
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PlanLetting-Bastion-SG

  ManagementSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPCPeeringConnection
    Properties:
      GroupDescription: Allos SSH from Bastion Host in VPC A
      VpcId: !Ref VPCB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: PlanLetting-Mgmt-SG

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPCPeeringConnection
    Properties:
      GroupDescription: Allow traffic from ALB and Management Instance
      VpcId: !Ref VPCA
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref ManagementSecurityGroup
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref ManagementSecurityGroup
      Tags:
        - Key: Name
          Value: PlanLetting-Web-SG

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: VPCPeeringConnection
    Properties:
      GroupDescription: Allows DB traffic from Web servers and Management EC2. Deny all else
      VpcId: !Ref VPCB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebSecurityGroup
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ManagementSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref ManagementSecurityGroup
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref ManagementSecurityGroup
      Tags:
        - Key: Name
          Value: PlanLetting-DB-SG
Outputs:
  VPCAId:
    Description: VPC A ID
    Value: !Ref VPCA
    Export:
      Name: PlanLetting-VPCAId
  VPCBId:
    Description: VPC B ID
    Value: !Ref VPCB
    Export:
      Name: PlanLetting-VPCBId
  VPCAPublicSubnet1Id:
    Value: !Ref VPCAPublicSubnet1
    Export:
      Name: PlanLetting-VPCAPubSub1
  VPCAPublicSubnet2Id:
    Value: !Ref VPCAPublicSubnet2
    Export:
      Name: PlanLetting-VPCAPubSub2
  VPCAPrivateSubnet1Id:
    Value: !Ref VPCAPrivateSubnet1
    Export:
      Name: PlanLetting-VPCAPrivSub1
  VPCAPrivateSubnet2Id:
    Value: !Ref VPCAPrivateSubnet2
    Export:
      Name: PlanLetting-VPCAPrivSub2
  VPCBPrivateSubnet1Id:
    Value: !Ref VPCBPrivateSubnet1
    Export:
      Name: PlanLetting-VPCBPrivSub1
  VPCBPrivateSubnet2Id:
    Value: !Ref VPCBPrivateSubnet2
    Export:
      Name: PlanLetting-VPCBPrivSub2
  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: PlanLetting-ALBSG
  WebSecurityGroupId:
    Value: !Ref WebSecurityGroup
    Export:
      Name: PlanLetting-WebSG
  DatabaseSecurityGroupId:
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: PlanLetting-DBSG
  BastionSecurityGroupId:
    Value: !Ref BastionSecurityGroup
    Export:
      Name: PlanLetting-BastionSG
  ManagementSecurityGroupId:
    Value: !Ref ManagementSecurityGroup
    Export:
      Name: PlanLetting-MgmtSG