name: Deploy CloudFormation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Repo
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: List Files
        run: ls -R
        working-directory: ${{ github.workspace }}
        
      - name: Deploy Stack 1 (Network)
        run: | 
          aws cloudformation deploy \
          --stack-name PlanLetting-Network \
          --template-file Templates/Network.yaml \
          --capabilities CAPABILITY_NAMED_IAM
          
      - name: Deploy Stack 2 (Application & Database)
        run: | 
          aws cloudformation deploy \
          --stack-name PlanLetting-App \
          --template-file Templates/application.yaml \
          --parameter-overrides DBPassword="${{ secrets.DB_PASSWORD }}" KeyName=vockey \
          --capabilities CAPABILITY_NAMED_IAM
          
      - name: Get Network Outputs
        run: | 
          aws cloudformation describe-stacks \
          --stack-name PlanLetting-App \
          --query "Stacks[0].Outputs[*].{Key:OutputKey,Value:OutputValue}" \
          --output table
